use crate::config::WafConfig;
use fancy_regex::Regex;
use once_cell::sync::Lazy;
use std::collections::HashSet;

// Include the pre-parsed rules generated by build.rs
mod generated {
    include!(concat!(env!("OUT_DIR"), "/waf_rules_generated.rs"));
}

pub struct CrsRule {
    pub id: String,
    pub regex: Regex,
    pub paranoia_level: u8,
}

pub static CRS_RULES: Lazy<Vec<CrsRule>> = Lazy::new(|| {
    let mut rules = Vec::new();

    // Add a broad SQLi regex to catch common patterns
    let broad_sqli = r#"(?i)(?:(?:\'|\"|%27|%22)\s*(?:OR|AND|UNION|SELECT|INSERT|UPDATE|DELETE|DROP|--|;)|(?:\'|\"|%27|%22)\s*\d+\s*=\s*\d+|\b(?:union|select|insert|update|delete|drop|alter|create|truncate|exec|xp_cmdshell|benchmark|sleep)\b|;\s*\b(?:select|insert|update|delete|drop|union)\b)"#;
    if let Ok(re) = Regex::new(broad_sqli) {
        rules.push(CrsRule {
            id: "GENERIC-SQLI".to_string(),
            regex: re,
            paranoia_level: 1,
        });
    }

    for (id, regex_str, paranoia_level) in generated::GENERATED_CRS_RULES {
        if let Ok(re) = Regex::new(regex_str) {
            rules.push(CrsRule {
                id: id.to_string(),
                regex: re,
                paranoia_level: *paranoia_level,
            });
        }
    }
    rules
});

pub struct WafEngine;

impl WafEngine {
    pub fn calculate_score(input: &str, config: &WafConfig) -> (i32, Vec<String>) {
        let mut score = 0;
        let mut matched = Vec::new();
        for rule in CRS_RULES.iter() {
            if rule.paranoia_level > config.rules.paranoia_level {
                continue;
            }
            if !config.rules.is_rule_enabled(&rule.id) {
                continue;
            }
            if let Ok(true) = rule.regex.is_match(input) {
                score += 5;
                matched.push(rule.id.clone());
            }
        }
        (score, matched)
    }

    pub fn analyze_request(
        path: &str,
        query: &str,
        headers: &std::collections::HashMap<String, String>,
        body: Option<&str>,
        config: &WafConfig,
    ) -> (i32, Vec<String>) {
        let mut total_score = 0;
        let mut matched_rules = HashSet::new();

        // Check path
        let decoded_path = urlencoding::decode(path).unwrap_or_else(|_| path.into());
        let (_, path_rules) = Self::calculate_score(&decoded_path, config);
        for rule_id in path_rules {
            if matched_rules.insert(rule_id) {
                total_score += 5;
            }
        }

        // Check query params
        if !query.is_empty() {
            let decoded_query = urlencoding::decode(query).unwrap_or_else(|_| query.into());
            let (_, query_rules) = Self::calculate_score(&decoded_query, config);
            for rule_id in query_rules {
                if matched_rules.insert(rule_id) {
                    total_score += 5;
                }
            }
        }

        // Check headers
        for (name, value) in headers {
            let name_lower = name.to_lowercase();
            if name_lower == "user-agent" || name_lower == "referer" || name_lower == "cookie" {
                let (_, header_rules) = Self::calculate_score(value, config);
                for rule_id in header_rules {
                    if matched_rules.insert(rule_id) {
                        total_score += 2;
                    }
                }
            }
        }

        // Check body
        if let Some(body_str) = body {
            let (_, body_rules) = Self::calculate_score(body_str, config);
            for rule_id in body_rules {
                if matched_rules.insert(rule_id) {
                    total_score += 5;
                }
            }
        }

        (total_score, matched_rules.into_iter().collect())
    }

    pub fn get_attack_types(rule_ids: &[String]) -> String {
        let mut types = HashSet::new();
        for id in rule_ids {
            if id.starts_with("930") {
                types.insert("Local File Inclusion (LFI)");
            } else if id.starts_with("931") {
                types.insert("Remote File Inclusion (RFI)");
            } else if id.starts_with("932") {
                types.insert("Remote Code Execution (RCE)");
            } else if id.starts_with("933") {
                types.insert("PHP Injection");
            } else if id.starts_with("934") {
                types.insert("Generic Attack");
            } else if id.starts_with("941") {
                types.insert("Cross-Site Scripting (XSS)");
            } else if id.starts_with("942") || id == "GENERIC-SQLI" {
                types.insert("SQL Injection (SQLi)");
            } else if id.starts_with("943") {
                types.insert("Session Fixation");
            } else {
                types.insert("Unknown Rule");
            }
        }
        let mut sorted_types: Vec<_> = types.into_iter().collect();
        sorted_types.sort();
        sorted_types.join(", ")
    }
}
